name: deploy2ahtprod.yml
on:
  workflow_dispatch:

concurrency: production_environment

jobs:
  deploy2ahprod:
    name: deploy2ahprod
    runs-on: ubuntu-latest    
    steps:
      - name: Docker 
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo su
            apt install git-all -y
            apt install docker-compose -y
            apt update -y && apt upgrade -y
            cd /root
            cd toolshop/practice-software-testing
            git pull 
            ls -la
            cd practice-software-testing
            docker-compose up -d
            docker ps -a
            docker images
          #host: ${{ secrets.HOST }}
          host: 109.176.250.82
          user: ahproduser
          key: ${{ secrets.PRIVATE_KEY}}
